### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by adarshk7** [uption/uption#19]
Add documentation in the proper format so that when uption is exported as a crate doc page could be autogenerated. Possibly add CI job to ensure documentation completeness.

- [x] Uption general documentation (how it works, architecture etc.)
- [x] Document configuration
- [x] Document collectors
- [x] Document exporters
- [x] Update code documentation (comments):
  - [x] Traits
  - [x] Exporters
  - [x] Collectors
  - [x] Module descriptions
  - [x] Structs important to the core functionality like collector and exporter schedulers

**Comment by ollipa** [comment]
I'm thinking that it is probably enough that we have documentation in Git repository as Markdown files at first. Later when we want to improve the documentation we could use some static page generator like [Hugo](https://gohugo.io/) or [Zola](https://www.getzola.org/).

**Comment by ollipa** [comment]
I started user documentation in wiki:
https://github.com/uption/uption/wiki

**Comment by ollipa** [comment]
@adarshk7, this should be done now :slightly_smiling_face:
