### ISSUE TITLE
Ping parsing fails if latency more than 100ms

### ISSUE THREAD

**Issue by ollipa** [uption/uption#39]
It seems that ping command doesn't return a float if ping latency is more than 100ms:
```
Reading configuration
Uption v0.2.0 started
Collector scheduler started
Exporter scheduler started
Failed to parse ping command output (source="ping_collector" context="PING example.com (93.184.216.34) 56(84) bytes of data.
64 bytes from 93.184.216.34 (93.184.216.34): icmp_seq=1 ttl=54 time=175 ms
```

The last line (statistics) still returns a float. We should change ping collector back to parsing latency from there.

**Comment by adarshk7** [comment]
In the case of ping (GNU inetutils) 1.9.2 this is still float 😅but yes, parsing from statistics line would be more versatile.
